version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
region = "ap-northeast-1"
s3_bucket = "lambda-opensea-artifact"
stack_name = "lambda-opensea"
