AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 900
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda.zip
      Runtime: nodejs16.x
      Handler: index.handler
      MemorySize: 512
