AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 900

Parameters:
  SsmParameter:
    Type: String
    Default: /lambda-opensea/server/dotenv
    Description: ssm parameter path

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Environment:
        Variables:
          SSM_PARAMETER: !Ref SsmParameter
      Policies:
        - AmazonSSMReadOnlyAccess
        - AmazonS3FullAccess
    Metadata:
      DockerTag: latest
      DockerContext: ./
      Dockerfile: Dockerfile
